all:
	(cd timerLib; make install)
	(cd button_demo; make)

clean:
	(cd timerLib; make clean)
	(cd blink_demo; make clean)
	(cd button_demo; make clean)
	(cd buzzer_demo; make clean)
	(cd dim_demo; make clean)
	rm -rf lib h

